image: oven/bun

cache:
  paths:
    - node_modules/
    - dist/
    - avifenc-v1.1.1

deploy:
  before_script:
    - git submodule update
    - bun install --frozen-lockfile
  script:
    - bun run build
    - bunx wrangler pages deploy dist --project-name aperturic-focus
