image: homebrew/brew

cache:
  paths:
    - node_modules/
    - dist/
    - avifenc-v1.1.1

deploy:
  before_script:
    - brew install git cloudflare-wrangler2 oven-sh/bun/bun
  script:
    - git submodule update
    - bun install --frozen-lockfile
    - bun run build
    - wrangler pages deploy dist --project-name aperturic-focus
