#!/bin/bash

# Upgrade bun before starting build
echo "Upgrading Bun"
bun upgrade --silent
echo "Done!"
echo

# Copy public files
echo "Copying files in public/..."
mkdir -p ./dist/
cp ./public/* ./dist/
echo "Done!"
echo

# Build CSS
echo "Building CSS..."
bun ./build-tools/css.ts
echo "Done!"
echo

# Build images
echo "Optimising images..."
mkdir -p ./tmp/
bun ./build-tools/images.ts
echo "Done!"
echo

# Build HTML
echo "Writing HTML..."
bun ./build-tools/html.ts
echo "Done!"
echo

# Cleanup
echo "Cleaning up..."
rm -rf ./tmp/
echo "Done!"
