#!/bin/bash

# Upgrade bun before starting build
echo "Upgrading Bun"
bun upgrade --silent
echo "Done!"
echo

# Copy public files
echo "Copying files in public/..."
mkdir -p ./dist/
cp ./public/* ./dist/
echo "Done!"
echo

# Build CSS
echo "Building CSS..."
bun ./build-tools/css.ts
echo "Done!"
echo

# Build images
echo "Optimising images and building HTML..."
bun ./build-tools/html.ts
echo "Done!"

