#!/bin/bash

mkdir ./dist/

# Copy favicon
cp ./src/favicon.ico ./dist/favicon.ico

# Build CSS
bun run ./scripts/build-css.ts

# Build HTML and images
bun run ./scripts/build-html.ts

# Copy images
cp ./node_modules/_images/ ./dist/_images/